DELETE FROM User;
INSERT INTO USER VALUES (10,'user10');
INSERT INTO USER VALUES (20,'user20');

INSERT INTO USER VALUES (30,'user30');
INSERT INTO USER VALUES (40,'用户40');

/****

    INSERT INTO USER VALUES (50, "用户;50");
 */
INSERT INTO USER VALUES (50, "用户;50");
INSERT INTO USER VALUES

(60, "user60"),

(70, "user;70");

# comment
-- comment
